services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  gateway:
    build:
        context: .
        dockerfile: gateway/Dockerfile
    extra_hosts:
      - proxy-host:host-gateway
    ports:
      - '9090:9090'
  third-party:
    image: 'wiremock/wiremock'
    volumes:
      - './third-party/mappings:/home/wiremock/mappings'
    ports:
      - '9091:8080'
  aws:
    image: 'localstack/localstack:latest'
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
    ports:
      - "127.0.0.1:4566:4566"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"