services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  gateway:
    build:
        context: .
        dockerfile: gateway/Dockerfile
    extra_hosts:
      - proxy-host:host-gateway
    ports:
      - '9090:9090'
